# Generated by Django 2.0.9 on 2019-08-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=5000)),
                ('capacity', models.IntegerField(default=30)),
                ('detail', models.TextField(max_length=1000)),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=1)),
                ('paid', models.IntegerField(default=0)),
                ('authority', models.CharField(default='none', max_length=200)),
                ('refid', models.CharField(default='none', max_length=200)),
                ('discount_pk', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('person_type', models.IntegerField(default=0)),
                ('detail_type', models.IntegerField(default=4)),
                ('guide_id', models.CharField(default='-', max_length=100)),
                ('university', models.CharField(default='-', max_length=100)),
                ('study_field', models.CharField(default='-', max_length=100)),
                ('student_id', models.CharField(default='-', max_length=100)),
                ('agancy', models.CharField(default='-', max_length=100)),
                ('city', models.CharField(default='-', max_length=100)),
                ('hotel', models.CharField(default='-', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.EventGroup'),
        ),
        migrations.AddField(
            model_name='discount',
            name='event_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.EventGroup'),
        ),
    ]
