# Generated by Django 2.2.4 on 2019-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('person_type', models.IntegerField()),
                ('detail_type', models.IntegerField()),
                ('guide_id', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('study_field', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('agancy', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
