# Generated by Django 2.2.4 on 2019-08-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_auto_20190806_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=5000)),
                ('capacity', models.IntegerField(default=30)),
                ('detail', models.TextField(max_length=1000)),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=1)),
                ('paid', models.IntegerField(default=0)),
                ('authority', models.CharField(default='none', max_length=200)),
                ('refid', models.CharField(default='none', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person')),
            ],
        ),
    ]
