# Generated by Django 2.1.9 on 2019-08-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
