# Generated by Django 2.2.4 on 2019-08-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_event_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_pk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.Event')),
            ],
        ),
    ]
