# Generated by Django 2.0.9 on 2019-08-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_event_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person'),
        ),
    ]
