# Generated by Django 2.2.4 on 2019-08-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0004_auto_20190815_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person'),
        ),
    ]
