# Generated by Django 2.0.9 on 2019-08-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0004_auto_20190815_1627'),
        ('registeration', '0004_auto_20190814_2152'),
    ]

    operations = [
    ]
