# Generated by Django 2.0.9 on 2019-08-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20190816_1657'),
        ('registeration', '0005_merge_20190816_1608'),
    ]

    operations = [
    ]
