# Generated by Django 2.2.4 on 2019-08-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20190816_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person'),
        ),
    ]
