# Generated by Django 2.0.9 on 2019-08-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0006_merge_20190816_2152'),
        ('registeration', '0006_auto_20190816_2152'),
    ]

    operations = [
    ]
