# Generated by Django 2.0.9 on 2019-08-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0007_merge_20190816_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='event',
        ),
        migrations.AddField(
            model_name='discount',
            name='event_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registeration.EventGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registeration.EventGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person'),
        ),
    ]
